### ISSUE TITLE
Integrate Auphonic audio processing API

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenly-cms#88] opened 2015-07-16 15:01 UTC
Low priority because it will basically require us to change our podcast upload workflow and i'm not super anxious to do that but this would allow us to offer audio processing as a service - we'd buy hours of processing in bulk and then charge podcasters in LTBc or BTC to use it.

https://auphonic.com/developers

**Comment by cryptonaut420** [comment] 2015-10-12 20:52
closing, duplicate of #105

**Closed by cryptonaut420** 2015-10-12 20:52 UTC
